spring.cloud.loadbalancer.ribbon.enabled = false

eureka.instance.preferIpAddress = true
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.serviceUrl.defaultZone = http://localhost:8070/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8074/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8074/realms/master/protocol/openid-connect/certs

services.product-service.url=http://localhost:8072/productservice
services.user-service.url=http://localhost:8072/userservice
services.ratings-aggregator.url=http://localhost:8072/revaggservice
services.warehouse-service.url=http://localhost:8072/warehouseservice
services.cart-service.url=http://localhost:8072/cartservice

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.schema.registry.url=http://localhost:8076

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.reflection=true

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.reflection=true
spring.kafka.consumer.properties.specific.avro.reader=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.enable.cache=true
management.metrics.distribution.percentiles-histogram.cache.gets=true
management.metrics.tags.cache.name=*
management.metrics.distribution.percentiles-histogram.http.server.requests=true