spring.cloud.loadbalancer.ribbon.enabled = false

management.endpoints.web.exposure.include=*

eureka.instance.preferIpAddress = true
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.serviceUrl.defaultZone = http://localhost:8070/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8074/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8074/realms/master/protocol/openid-connect/certs

services.product-service.url=http://localhost:8072/productservice
services.user-service.url=http://localhost:8072/userservice
services.ratings-aggregator.url=http://localhost:8072/revaggservice