server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      dicovery.locator:
        enabled: true
        lowerCaseServiceId: true
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/productservice/**
              filters:
                - RewritePath=/productservice/(?<path>.*), /$\{path}
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orderservice/**
              filters:
                - RewritePath=/orderservice/(?<path>.*), /$\{path}
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/authservice/**
              filters:
                - RewritePath=/authservice/(?<path>.*), /$\{path}
            - id: review-aggregate-service
              uri: lb://review-aggregate-service
              predicates:
                  - Path=/revaggservice/**
              filters:
                - RewritePath=/revaggservice/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted