server.port=8073

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

spring.security.oauth2.client.registration.my-client.client-id=${oauth2.client-id}
spring.security.oauth2.client.registration.my-client.client-secret=${oauth2.client-secret}
spring.security.oauth2.client.registration.my-client.authorization-grant-type=password
spring.security.oauth2.client.registration.my-client.scope=openid,profile,email
spring.security.oauth2.client.provider.my-client.issuer-uri=http://localhost:8085/realms/master
spring.security.oauth2.client.provider.my-client.token-uri=http://localhost:8085/realms/master/protocol/openid-connect/token