server.port=8073

spring.security.oauth2.client.registration.my-client.client-id=market-frontend
spring.security.oauth2.client.registration.my-client.client-secret=xB1D8FSu9p7N6GcOUJQ7mv9gDxPUKNmV
spring.security.oauth2.client.registration.my-client.authorization-grant-type=password
spring.security.oauth2.client.registration.my-client.scope=openid,profile,email
spring.security.oauth2.client.provider.my-client.issuer-uri=http://localhost:8085/realms/master
spring.security.oauth2.client.provider.my-client.token-uri=http://localhost:8085/realms/master/protocol/openid-connect/token