server.port=8082

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
