CREATE TABLE IF NOT EXISTS rating_projection(
    product_uuid UUID PRIMARY KEY,
    cnt BIGINT NOT NULL DEFAULT 0,
    sum BIGINT NOT NULL DEFAULT 0,
    avg NUMERIC(4,2) NOT NULL DEFAULT 0.0,
    b1 BIGINT NOT NULL DEFAULT 0,
    b2 BIGINT NOT NULL DEFAULT 0,
    b3 BIGINT NOT NULL DEFAULT 0,
    b4 BIGINT NOT NULL DEFAULT 0,
    b5 BIGINT NOT NULL DEFAULT 0,
    last_review_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);